### PR TITLE
updating readme for a test pull request

### PR DESCRIPTION
**Pull request by coreydaley**
A pull request to check that the CI/CD is working correctly

### CODE REVIEW

**Review by adambkaplan — COMMENTED** [review]
/approve

**Comment by adambkaplan** [comment]
/hold

I don't see any `tide` status check.

**Comment by coreydaley** [comment]
I have opened https://github.com/openshift/release/pull/12337 to hopefully fix the tide status issue

**Review by adambkaplan — APPROVED** [review]
/lgtm

**Pull request merged**
